title: "Classifying American Sign language into English letters"
description: "Bahjat Abugharbieh, Hasan Naseer, Luke LaScala, Willson White, Muhammed Abdul Bari Butabalbadi Mamba"
theme: jekyll-theme-cayman
