title: "Role of American Sign Language (ASL) in MINST DataSet"
description: "Bajhat Abugharbieh, Hasan Naseer, Luke LaScala, Willson White, Muhammed Abdul Bari Butabalbadi Mamba"
theme: jekyll-theme-cayman
